/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ajudaControl;
import controle.orcamentoControl;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultCellEditor;
import modelo.Contrato;
import modelo.Peca;

/**
 * 
 * @author milson
 */
public class Orcamento extends javax.swing.JFrame {
    // Creates new form Orcamento
    public Orcamento() {
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jSpinnerPreço = new javax.swing.JSpinner();
        jPanelTelaOrçamento = new javax.swing.JPanel();
        ButtonExportar = new javax.swing.JButton();
        ButtonSalvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nomeDoCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Fone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enderecoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        localPerfuracao = new javax.swing.JTextField();
        Type = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        totalGeral = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        emailCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clienteCEP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        clienteNumero = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemGuiaUsuario = new javax.swing.JMenuItem();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenuItem();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peças", "Mão-de-obra", "Verba", "Metro", "Horas" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Orçamento");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanelTelaOrçamento.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTelaOrçamento.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), null));

        ButtonExportar.setText("Exportar");
        ButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExportarActionPerformed(evt);
            }
        });

        ButtonSalvar.setText("Salvar");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        nomeDoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeDoClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Fone:");

        Fone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoneActionPerformed(evt);
            }
        });

        jLabel3.setText("Endereço");

        enderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Local da Perfuração");

        localPerfuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localPerfuracaoActionPerformed(evt);
            }
        });

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contrato", "Orçamento" }));

        totalGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalGeralActionPerformed(evt);
            }
        });

        jLabel5.setText("Total Geral");

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Unidade", "Descrição", "Quantidade", "Preço", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabela.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(jTabela);
        if (jTabela.getColumnModel().getColumnCount() > 0) {
            jTabela.getColumnModel().getColumn(0).setResizable(false);
            jTabela.getColumnModel().getColumn(0).setPreferredWidth(132);
            jTabela.getColumnModel().getColumn(0).setCellEditor(new DefaultCellEditor(jComboBox2));
            jTabela.getColumnModel().getColumn(1).setResizable(false);
            jTabela.getColumnModel().getColumn(1).setPreferredWidth(410);
            jTabela.getColumnModel().getColumn(2).setResizable(false);
            jTabela.getColumnModel().getColumn(3).setResizable(false);
            jTabela.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel6.setText("e-Mail");

        jLabel7.setText("CEP:");

        clienteCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteCEPActionPerformed(evt);
            }
        });

        jLabel8.setText("Número:");

        javax.swing.GroupLayout jPanelTelaOrçamentoLayout = new javax.swing.GroupLayout(jPanelTelaOrçamento);
        jPanelTelaOrçamento.setLayout(jPanelTelaOrçamentoLayout);
        jPanelTelaOrçamentoLayout.setHorizontalGroup(
            jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3)
            .addGroup(jPanelTelaOrçamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTelaOrçamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTelaOrçamentoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(localPerfuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Type, 0, 168, Short.MAX_VALUE))
                    .addGroup(jPanelTelaOrçamentoLayout.createSequentialGroup()
                        .addComponent(ButtonExportar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonSalvar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelTelaOrçamentoLayout.createSequentialGroup()
                        .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTelaOrçamentoLayout.createSequentialGroup()
                                .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanelTelaOrçamentoLayout.createSequentialGroup()
                                        .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailCliente))
                                    .addGroup(jPanelTelaOrçamentoLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTelaOrçamentoLayout.createSequentialGroup()
                                .addComponent(enderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fone)
                            .addComponent(clienteCEP)
                            .addComponent(clienteNumero))))
                .addContainerGap())
        );
        jPanelTelaOrçamentoLayout.setVerticalGroup(
            jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaOrçamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(enderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(clienteCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(clienteNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(localPerfuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTelaOrçamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalvar)
                    .addComponent(ButtonExportar))
                .addContainerGap())
        );

        jMenuAjuda.setText("Ajuda");

        jMenuItemGuiaUsuario.setText("Guia do Usuário");
        jMenuItemGuiaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGuiaUsuarioActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemGuiaUsuario);

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuHelp.setText("Help");
        jMenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHelpActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuHelp);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTelaOrçamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTelaOrçamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(818, 881));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExportarActionPerformed
        orcamentoControl.generatePdf(this);
    }//GEN-LAST:event_ButtonExportarActionPerformed

    private void nomeDoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeDoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeDoClienteActionPerformed

    private void FoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoneActionPerformed

    private void enderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoClienteActionPerformed

    private void localPerfuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localPerfuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localPerfuracaoActionPerformed

    private void totalGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalGeralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalGeralActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        // TODO add your handling code here:
        orcamentoControl.saveNewContractToFile(this, this.contrato);
        orcamentoControl.getIDS();
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void clienteCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteCEPActionPerformed

    private void jMenuItemGuiaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuiaUsuarioActionPerformed
        
        ajudaControl.displayManuel();
        
    }//GEN-LAST:event_jMenuItemGuiaUsuarioActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed

        ajudaControl.displaySobre();
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHelpActionPerformed
        
        ajudaControl.displayHelp();
        
    }//GEN-LAST:event_jMenuHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Orcamento().setVisible(true);
        });
    }
    
    public Contrato contrato = new Contrato();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonExportar;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JTextField Fone;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.JTextField clienteCEP;
    private javax.swing.JTextField clienteNumero;
    private javax.swing.JTextField emailCliente;
    private javax.swing.JTextField enderecoCliente;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuHelp;
    private javax.swing.JMenuItem jMenuItemGuiaUsuario;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JPanel jPanelTelaOrçamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinnerPreço;
    private javax.swing.JTable jTabela;
    private javax.swing.JTextField localPerfuracao;
    private javax.swing.JTextField nomeDoCliente;
    private javax.swing.JTextField totalGeral;
    // End of variables declaration//GEN-END:variables

    public void setNome(String name){
        nomeDoCliente.setText(name);
    }
    
    public String getNome(){
        return nomeDoCliente.getText();
    }
    
    public void setEndereco(String endereco){
        enderecoCliente.setText(endereco);
    }
    
    public String getEndereco(){
        return enderecoCliente.getText();
    }
    
    public void setLocalPerfuracao(String local){
        localPerfuracao.setText(local);
    }
    
    public String getLocalPerfuracao(){
        return localPerfuracao.getText();
    }
    
    public String getEmail(){
        return emailCliente.getText();
    }
    
    public void setEmail(String email){
        emailCliente.setText(email);
    }
    
    public void setFone(String fone){
        Fone.setText(fone);
    }
    
    public String getFone(){
        return Fone.getText();
    }
    
    public String getCep(){
        return clienteCEP.getText();
    }
    
    public void setCep(String cep){
        clienteCEP.setText(cep);
    }
    
    public void setNumber(String number){
        clienteNumero.setText(number);
    }
    
    public String getNumber(){
        return clienteNumero.getText();
    }
    
    public void setTotal(String total){
        totalGeral.setText(total);
    }
    
    public boolean getContractType(){
        return Type.getSelectedIndex() == 0;
    }
    
    public void setContractType(int selected){
        Type.setSelectedIndex(selected);
    }
    
    public void setColuna0(){
        /* TODO */
        /* coluna referente ao tipo */
    }
    
    public void setColuna1(ArrayList<String> toSet){
        /* coluna referente a descricao */
        for(int i = 0; i < toSet.size(); i++)
            this.jTabela.setValueAt(toSet, i, 1);
   }
    
    public void setColuna2(ArrayList<Integer> toSet){
        /* coluna referente a quantidade */
        for(int i = 0; i < toSet.size(); i++)
            this.jTabela.setValueAt(toSet, i, 2);
    }
    
    public void setColuna3(ArrayList<Double> toSet){
        /* coluna referente ao preco */
        for(int i = 0; i < toSet.size(); i++)
            this.jTabela.setValueAt(toSet, i, 3);
    }
    
    public void setColuna4(ArrayList<Double> toSet) {
        /* coluna referente ao total */
        for(int i = 0; i < toSet.size(); i++)
            this.jTabela.setValueAt(toSet, i, 4);
    }
    
    public HashMap<String, Peca> getColunas(){
        HashMap<String, Peca> PM = new HashMap<>();
        
        String Name;
        String Tipo;
        int Quant;
        double Price;
        /* percorre os todo os campos da tabela, achar mameira melhor de fazer isso */
        for (int i = 0; i < 28; i++){
            if(this.jTabela.getValueAt(i, 0) != null 
            && this.jTabela.getValueAt(i, 1) != null 
            && this.jTabela.getValueAt(i, 2) != null
            && this.jTabela.getValueAt(i, 3) != null){
            
                Tipo = this.jTabela.getValueAt(i, 0).toString();
                Name = this.jTabela.getValueAt(i, 1).toString();
                Quant = Integer.parseInt(this.jTabela.getValueAt(i, 2).toString());
                Price = Double.parseDouble(this.jTabela.getValueAt(i, 3).toString());
            
                if(Tipo != null && Name != null && Quant != 0 && Price != 0){
                    Peca peca = new Peca(Name, Tipo, Quant, Price);
                    PM.put(peca.getName(), peca);
                }
            }
        }
        return PM;
    }
}
